// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailablePorts() {
  return window['go']['main']['App']['GetAvailablePorts']();
}

export function StartPolling() {
  return window['go']['main']['App']['StartPolling']();
}

export function StopPolling() {
  return window['go']['main']['App']['StopPolling']();
}
