// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSavedSerialConfig() {
  return window['go']['main']['App']['ClearSavedSerialConfig']();
}

export function GetAvailablePorts() {
  return window['go']['main']['App']['GetAvailablePorts']();
}

export function GetElectricalData() {
  return window['go']['main']['App']['GetElectricalData']();
}

export function LoadSavedSerialConfig() {
  return window['go']['main']['App']['LoadSavedSerialConfig']();
}

export function SaveSavedSerialConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveSavedSerialConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartPolling() {
  return window['go']['main']['App']['StartPolling']();
}

export function StopPolling() {
  return window['go']['main']['App']['StopPolling']();
}

export function UpdateSerialConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateSerialConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}
